/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ParticipantDto } from './participantDto';


/**
 * Entity to be saved
 */
export interface EntryDto { 
    id: string;
    paid: boolean;
    accepted: boolean;
    participants?: Set<ParticipantDto>;
    invoices?: Set<string>;
}

